---
title: "Lectura 9"
author: "Sofia Gacitua"
date: "2024-11-10"
output: html_document
---

Script 11.5: Resultado de la prueba de Wilcoxon-Mann-Whitney para el ejemplo

```{r}
# Ingresar los datos.
Interfaz_A <- c(2.7, 6.6, 1.6, 5.1, 3.7, 6.1, 5.0, 1.4, 1.8, 1.5, 3.0, 5.3)
Interfaz_B <- c(5.0, 1.4, 5.6, 4.6, 6.7, 2.7, 1.3, 6.3, 3.7, 1.3 , 6.8)

# Establecer nivel de significación.
alfa <- 0.05

# Hacer la prueba de Mann-Whitney.
prueba <- wilcox.test(Interfaz_A, Interfaz_B, alternative = "two.sided",
                      conf.level = 1 - alfa)
print(prueba)
```

Script 11.6: Prueba de rangos con signo de Wilcoxon para el ejemplo

```{r}
# Ingresar los datos.
Interfaz_A <- c(2.9, 6.1, 6.7, 4.7, 6.4, 5.7, 2.7, 6.9, 1.7, 6.4)
Interfaz_B <- c(6.0, 2.8, 1.3, 4.7, 3.1, 1.8, 2.9, 4.0, 2.3, 1.6)

# Establecer nivel de significación.
alfa <- 0.05

# Hacer la prueba de rangos con signo de Wilcoxon.
prueba <- wilcox.test(Interfaz_A, Interfaz_B, paired = TRUE,
                      alternative = "greater", conf.level = 1 - alfa)
print(prueba)
```
